language: go

install:
  - make devel

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - make all
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      make publish
      if [ $TARGET_PLATFORM = 'linux' ]; then
        make release
      fi
    fi

matrix:
  include:
    - go: 1.7
      env: TARGET_PLATFORM=linux
    - go: 1.7
      env: TARGET_PLATFORM=darwin

env:
  global:
    - secure: "ABW2YjCq0xhkWbnrazL1IhKaIN7zr90BQWmeC3uII/4mQJ5sxY0sssFSMWM1hMDDzWKjpXTeVJlhjqyPQ9LHceLjA74UrPBKX8saKg0f4ZcfbjFyXSCEme6nDl4ktYuuqDFlTNdokpOtb6mHQiPLHahNkIVjL48s32WoaCEZsKg="
